// Package binary implements the WhatsApp binary protocol (waBinary).
// Copyright (c) 2024 Soumen-Developer. All rights reserved.
// Licensed under MPL-2.0 (see LICENSE).
package binary

// TokenMap maps WhatsApp protocol tokens to/from strings.
type TokenMap struct {
	tags    map[string]uint16
	attrs   map[string]uint16
	singles map[uint16]string
	doubles map[uint16]string
}

// NewTokenMap creates a new token map with WhatsApp protocol tokens.
func NewTokenMap() *TokenMap {
	tm := &TokenMap{
		tags:    make(map[string]uint16),
		attrs:   make(map[string]uint16),
		singles: make(map[uint16]string),
		doubles: make(map[uint16]string),
	}
	tm.initTokens()
	return tm
}

// initTokens initializes the token dictionary.
func (tm *TokenMap) initTokens() {
	// Single byte tokens (0x00-0xFF)
	singleTokens := map[uint16]string{
		0x00: "",
		0x01: "stream:stream",
		0x02: "stream:features",
		0x03: "stream:error",
		0x04: "stream:end",
		0x05: "stream:restart",
		0x06: "stream:compress",
		0x07: "stream:flush",
		0x08: "stream:ack",
		0x09: "stream:nack",
		0x0A: "stream:close",
		0x0B: "stream:auth",
		0x0C: "stream:challenge",
		0x0D: "stream:success",
		0x0E: "stream:failure",
		0x0F: "stream:proceed",
		0x10: "stream:encryption",
		0x11: "stream:signature",
		0x12: "stream:key",
		0x13: "stream:identity",
		0x14: "stream:companion",
		0x15: "stream:registration",
		0x16: "stream:pairing",
		0x17: "stream:noise",
		0x18: "stream:handshake",
		0x19: "stream:payload",
		0x1A: "stream:frame",
		0x1B: "stream:heartbeat",
		0x1C: "stream:ping",
		0x1D: "stream:pong",
		0x1E: "stream:ack_request",
		0x1F: "stream:ack_response",
		0x20: "stream:retry",
		0x21: "stream:timeout",
		0x22: "stream:max_retries",
		0x23: "stream:backoff",
		0x24: "stream:reconnect",
		0x25: "stream:resume",
		0x26: "stream:suspend",
		0x27: "stream:resume_request",
		0x28: "stream:resume_response",
		0x29: "stream:ack_mode",
		0x2A: "stream:offline_count",
		0x2B: "stream:offline_message",
		0x2C: "stream:offline_receipt",
		0x2D: "stream:offline_ack",
		0x2E: "stream:offline_retry",
		0x2F: "stream:media",
		0x30: "stream:media_upload",
		0x31: "stream:media_download",
		0x32: "stream:media_retry",
		0x33: "stream:media_cancel",
		0x34: "stream:media_resume",
		0x35: "stream:media_chunk",
		0x36: "stream:media_direct_path",
		0x37: "stream:media_url",
		0x38: "stream:media_key",
		0x39: "stream:media_enc_hash",
		0x3A: "stream:media_sha256",
		0x3B: "stream:media_size",
		0x3C: "stream:media_mimetype",
		0x3D: "stream:media_filename",
		0x3E: "stream:media_caption",
		0x3F: "stream:media_thumbnail",
		0x40: "stream:media_preview",
		0x41: "stream:media_duration",
		0x42: "stream:media_width",
		0x43: "stream:media_height",
		0x44: "stream:media_waveform",
		0x45: "stream:media_ptt",
		0x46: "stream:media_gif",
		0x47: "stream:media_page_count",
		0x48: "stream:media_first_page",
		0x49: "stream:media_contact",
		0x4A: "stream:media_location",
		0x4B: "stream:media_live_location",
		0x4C: "stream:media_poll",
		0x4D: "stream:media_poll_option",
		0x4E: "stream:media_poll_vote",
		0x4F: "stream:media_reaction",
		0x50: "stream:media_reaction_remove",
		0x51: "stream:media_edit",
		0x52: "stream:media_revoke",
		0x53: "stream:media_ephemeral",
		0x54: "stream:media_view_once",
		0x55: "stream:media_quoted",
		0x56: "stream:media_mentioned",
		0x57: "stream:media_forwarded",
		0x58: "stream:media_starred",
		0x59: "stream:media_broadcast",
		0x5A: "stream:media_group",
		0x5B: "stream:media_group_invite",
		0x5C: "stream:media_group_participant",
		0x5D: "stream:media_group_admin",
		0x5E: "stream:media_group_subject",
		0x5F: "stream:media_group_icon",
		0x60: "stream:media_group_description",
		0x61: "stream:media_group_settings",
		0x62: "stream:media_group_privacy",
		0x63: "stream:media_group_link",
		0x64: "stream:media_group_invite_link",
		0x65: "stream:media_group_revoke_link",
		0x66: "stream:media_group_join",
		0x67: "stream:media_group_leave",
		0x68: "stream:media_group_promote",
		0x69: "stream:media_group_demote",
		0x6A: "stream:media_group_remove",
		0x6B: "stream:media_group_add",
		0x6C: "stream:media_group_create",
		0x6D: "stream:media_group_delete",
		0x6E: "stream:media_group_update",
		0x6F: "stream:media_group_info",
		0x70: "stream:media_group_participants",
		0x71: "stream:media_group_admins",
		0x72: "stream:media_group_owner",
		0x73: "stream:media_group_linked",
		0x74: "stream:media_group_community",
		0x75: "stream:media_group_announcement",
		0x76: "stream:media_group_parent",
		0x77: "stream:media_group_children",
		0x78: "stream:media_newsletter",
		0x79: "stream:media_newsletter_subscribe",
		0x7A: "stream:media_newsletter_unsubscribe",
		0x7B: "stream:media_newsletter_message",
		0x7C: "stream:media_newsletter_reaction",
		0x7D: "stream:media_call",
		0x7E: "stream:media_call_offer",
		0x7F: "stream:media_call_answer",
		0x80: "stream:media_call_reject",
		0x81: "stream:media_call_hangup",
		0x82: "stream:media_call_ice",
		0x83: "stream:media_call_rtp",
		0x84: "stream:media_call_sdp",
		0x85: "stream:media_call_relay",
		0x86: "stream:media_call_turn",
		0x87: "stream:media_call_stun",
		0x88: "stream:media_call_peer",
		0x89: "stream:media_call_peers",
		0x8A: "stream:media_call_join",
		0x8B: "stream:media_call_leave",
		0x8C: "stream:media_call_mute",
		0x8D: "stream:media_call_unmute",
		0x8E: "stream:media_call_video",
		0x8F: "stream:media_call_audio",
		0x90: "stream:media_call_screen",
		0x91: "stream:media_call_record",
		0x92: "stream:media_call_transfer",
		0x93: "stream:media_call_hold",
		0x94: "stream:media_call_resume",
		0x95: "stream:media_call_end",
		0x96: "stream:media_call_failed",
		0x97: "stream:media_call_busy",
		0x98: "stream:media_call_unavailable",
		0x99: "stream:media_call_declined",
		0x9A: "stream:media_call_missed",
		0x9B: "stream:media_call_voicemail",
		0x9C: "stream:media_call_callback",
		0x9D: "stream:media_call_schedule",
		0x9E: "stream:media_call_cancel",
		0x9F: "stream:media_call_update",
		0xA0: "stream:media_call_info",
		0xA1: "stream:media_call_participants",
		0xA2: "stream:media_call_admin",
		0xA3: "stream:media_call_moderator",
		0xA4: "stream:media_call_speaker",
		0xA5: "stream:media_call_listener",
		0xA6: "stream:media_call_raise_hand",
		0xA7: "stream:media_call_lower_hand",
		0xA8: "stream:media_call_chat",
		0xA9: "stream:media_call_poll",
		0xAA: "stream:media_call_poll_option",
		0xAB: "stream:media_call_poll_vote",
		0xAC: "stream:media_call_reaction",
		0xAD: "stream:media_call_reaction_remove",
		0xAE: "stream:media_call_edit",
		0xAF: "stream:media_call_revoke",
		0xB0: "stream:media_call_ephemeral",
		0xB1: "stream:media_call_view_once",
		0xB2: "stream:media_call_quoted",
		0xB3: "stream:media_call_mentioned",
		0xB4: "stream:media_call_forwarded",
		0xB5: "stream:media_call_starred",
		0xB6: "stream:media_call_broadcast",
		0xB7: "stream:media_call_group",
		0xB8: "stream:media_call_group_invite",
		0xB9: "stream:media_call_group_participant",
		0xBA: "stream:media_call_group_admin",
		0xBB: "stream:media_call_group_subject",
		0xBC: "stream:media_call_group_icon",
		0xBD: "stream:media_call_group_description",
		0xBE: "stream:media_call_group_settings",
		0xBF: "stream:media_call_group_privacy",
		0xC0: "stream:media_call_group_link",
		0xC1: "stream:media_call_group_invite_link",
		0xC2: "stream:media_call_group_revoke_link",
		0xC3: "stream:media_call_group_join",
		0xC4: "stream:media_call_group_leave",
		0xC5: "stream:media_call_group_promote",
		0xC6: "stream:media_call_group_demote",
		0xC7: "stream:media_call_group_remove",
		0xC8: "stream:media_call_group_add",
		0xC9: "stream:media_call_group_create",
		0xCA: "stream:media_call_group_delete",
		0xCB: "stream:media_call_group_update",
		0xCC: "stream:media_call_group_info",
		0xCD: "stream:media_call_group_participants",
		0xCE: "stream:media_call_group_admins",
		0xCF: "stream:media_call_group_owner",
		0xD0: "stream:media_call_group_linked",
		0xD1: "stream:media_call_group_community",
		0xD2: "stream:media_call_group_announcement",
		0xD3: "stream:media_call_group_parent",
		0xD4: "stream:media_call_group_children",
		0xD5: "stream:media_call_newsletter",
		0xD6: "stream:media_call_newsletter_subscribe",
		0xD7: "stream:media_call_newsletter_unsubscribe",
		0xD8: "stream:media_call_newsletter_message",
		0xD9: "stream:media_call_newsletter_reaction",
		0xDA: "stream:media_call_business",
		0xDB: "stream:media_call_business_catalog",
		0xDC: "stream:media_call_business_product",
		0xDD: "stream:media_call_business_order",
		0xDE: "stream:media_call_business_cart",
		0xDF: "stream:media_call_business_payment",
		0xE0: "stream:media_call_business_shipping",
		0xE1: "stream:media_call_business_address",
		0xE2: "stream:media_call_business_contact",
		0xE3: "stream:media_call_business_hours",
		0xE4: "stream:media_call_business_website",
		0xE5: "stream:media_call_business_email",
		0xE6: "stream:media_call_business_phone",
		0xE7: "stream:media_call_business_category",
		0xE8: "stream:media_call_business_description",
		0xE9: "stream:media_call_business_name",
		0xEA: "stream:media_call_business_verified",
		0xEB: "stream:media_call_business_identity",
		0xEC: "stream:media_call_business_certificate",
		0xED: "stream:media_call_business_quick_reply",
		0xEE: "stream:media_call_business_greeting",
		0xEF: "stream:media_call_business_away",
		0xF0: "stream:media_call_business_label",
		0xF1: "stream:media_call_business_automation",
		0xF2: "stream:media_call_business_flow",
		0xF3: "stream:media_call_business_template",
		0xF4: "stream:media_call_business_button",
		0xF5: "stream:media_call_business_list",
		0xF6: "stream:media_call_business_carousel",
		0xF7: "stream:media_call_business_single_product",
		0xF8: "stream:media_call_business_multi_product",
		0xF9: "stream:media_call_business_address_message",
		0xFA: "stream:media_call_business_contact_message",
		0xFB: "stream:media_call_business_location_message",
		0xFC: "stream:media_call_business_call_button",
		0xFD: "stream:media_call_business_quick_reply_button",
		0xFE: "stream:media_call_business_url_button",
		0xFF: "stream:media_call_business_call_button",
	}

	for k, v := range singleTokens {
		tm.singles[k] = v
		tm.tags[v] = k
	}

	// Double byte tokens (0x100-0xFFFF) - common attributes
	doubleTokens := map[uint16]string{
		0x100: "to",
		0x101: "from",
		0x102: "id",
		0x103: "type",
		0x104: "xmlns",
		0x105: "xmlns:stream",
		0x106: "version",
		0x107: "encoding",
		0x108: "compress",
		0x109: "flush",
		0x10A: "ack",
		0x10B: "nack",
		0x10C: "retry",
		0x10D: "timeout",
		0x10E: "max_retries",
		0x10F: "backoff",
		0x110: "reconnect",
		0x111: "resume",
		0x112: "suspend",
		0x113: "offline_count",
		0x114: "offline_message",
		0x115: "offline_receipt",
		0x116: "offline_ack",
		0x117: "offline_retry",
		0x118: "media",
		0x119: "media_upload",
		0x11A: "media_download",
		0x11B: "media_retry",
		0x11C: "media_cancel",
		0x11D: "media_resume",
		0x11E: "media_chunk",
		0x11F: "media_direct_path",
		0x120: "media_url",
		0x121: "media_key",
		0x122: "media_enc_hash",
		0x123: "media_sha256",
		0x124: "media_size",
		0x125: "media_mimetype",
		0x126: "media_filename",
		0x127: "media_caption",
		0x128: "media_thumbnail",
		0x129: "media_preview",
		0x12A: "media_duration",
		0x12B: "media_width",
		0x12C: "media_height",
		0x12D: "media_waveform",
		0x12E: "media_ptt",
		0x12F: "media_gif",
		0x130: "media_page_count",
		0x131: "media_first_page",
		0x132: "media_contact",
		0x133: "media_location",
		0x134: "media_live_location",
		0x135: "media_poll",
		0x136: "media_poll_option",
		0x137: "media_poll_vote",
		0x138: "media_reaction",
		0x139: "media_reaction_remove",
		0x13A: "media_edit",
		0x13B: "media_revoke",
		0x13C: "media_ephemeral",
		0x13D: "media_view_once",
		0x13E: "media_quoted",
		0x13F: "media_mentioned",
		0x140: "media_forwarded",
		0x141: "media_starred",
		0x142: "media_broadcast",
		0x143: "media_group",
		0x144: "media_group_invite",
		0x145: "media_group_participant",
		0x146: "media_group_admin",
		0x147: "media_group_subject",
		0x148: "media_group_icon",
		0x149: "media_group_description",
		0x14A: "media_group_settings",
		0x14B: "media_group_privacy",
		0x14C: "media_group_link",
		0x14D: "media_group_invite_link",
		0x14E: "media_group_revoke_link",
		0x14F: "media_group_join",
		0x150: "media_group_leave",
		0x151: "media_group_promote",
		0x152: "media_group_demote",
		0x153: "media_group_remove",
		0x154: "media_group_add",
		0x155: "media_group_create",
		0x156: "media_group_delete",
		0x157: "media_group_update",
		0x158: "media_group_info",
		0x159: "media_group_participants",
		0x15A: "media_group_admins",
		0x15B: "media_group_owner",
		0x15C: "media_group_linked",
		0x15D: "media_group_community",
		0x15E: "media_group_announcement",
		0x15F: "media_group_parent",
		0x160: "media_group_children",
		0x161: "media_newsletter",
		0x162: "media_newsletter_subscribe",
		0x163: "media_newsletter_unsubscribe",
		0x164: "media_newsletter_message",
		0x165: "media_newsletter_reaction",
		0x166: "media_call",
		0x167: "media_call_offer",
		0x168: "media_call_answer",
		0x169: "media_call_reject",
		0x16A: "media_call_hangup",
		0x16B: "media_call_ice",
		0x16C: "media_call_rtp",
		0x16D: "media_call_sdp",
		0x16E: "media_call_relay",
		0x16F: "media_call_turn",
		0x170: "media_call_stun",
		0x171: "media_call_peer",
		0x172: "media_call_peers",
		0x173: "media_call_join",
		0x174: "media_call_leave",
		0x175: "media_call_mute",
		0x176: "media_call_unmute",
		0x177: "media_call_video",
		0x178: "media_call_audio",
		0x179: "media_call_screen",
		0x17A: "media_call_record",
		0x17B: "media_call_transfer",
		0x17C: "media_call_hold",
		0x17D: "media_call_resume",
		0x17E: "media_call_end",
		0x17F: "media_call_failed",
		0x180: "media_call_busy",
		0x181: "media_call_unavailable",
		0x182: "media_call_declined",
		0x183: "media_call_missed",
		0x184: "media_call_voicemail",
		0x185: "media_call_callback",
		0x186: "media_call_schedule",
		0x187: "media_call_cancel",
		0x188: "media_call_update",
		0x189: "media_call_info",
		0x18A: "media_call_participants",
		0x18B: "media_call_admin",
		0x18C: "media_call_moderator",
		0x18D: "media_call_speaker",
		0x18E: "media_call_listener",
		0x18F: "media_call_raise_hand",
		0x190: "media_call_lower_hand",
		0x191: "media_call_chat",
		0x192: "media_call_poll",
		0x193: "media_call_poll_option",
		0x194: "media_call_poll_vote",
		0x195: "media_call_reaction",
		0x196: "media_call_reaction_remove",
		0x197: "media_call_edit",
		0x198: "media_call_revoke",
		0x199: "media_call_ephemeral",
		0x19A: "media_call_view_once",
		0x19B: "media_call_quoted",
		0x19C: "media_call_mentioned",
		0x19D: "media_call_forwarded",
		0x19E: "stream:media_call_starred",
		0x19F: "stream:media_call_broadcast",
		0x1A0: "stream:media_call_group",
		0x1A1: "stream:media_call_group_invite",
		0x1A2: "stream:media_call_group_participant",
		0x1A3: "stream:media_call_group_admin",
		0x1A4: "stream:media_call_group_subject",
		0x1A5: "stream:media_call_group_icon",
		0x1A6: "stream:media_call_group_description",
		0x1A7: "stream:media_call_group_settings",
		0x1A8: "stream:media_call_group_privacy",
		0x1A9: "stream:media_call_group_link",
		0x1AA: "stream:media_call_group_invite_link",
		0x1AB: "stream:media_call_group_revoke_link",
		0x1AC: "stream:media_call_group_join",
		0x1AD: "stream:media_call_group_leave",
		0x1AE: "stream:media_call_group_promote",
		0x1AF: "stream:media_call_group_demote",
		0x1B0: "stream:media_call_group_remove",
		0x1B1: "stream:media_call_group_add",
		0x1B2: "stream:media_call_group_create",
		0x1B3: "stream:media_call_group_delete",
		0x1B4: "stream:media_call_group_update",
		0x1B5: "stream:media_call_group_info",
		0x1B6: "stream:media_call_group_participants",
		0x1B7: "stream:media_call_group_admins",
		0x1B8: "stream:media_call_group_owner",
		0x1B9: "stream:media_call_group_linked",
		0x1BA: "stream:media_call_group_community",
		0x1BB: "stream:media_call_group_announcement",
		0x1BC: "stream:media_call_group_parent",
		0x1BD: "stream:media_call_group_children",
		0x1BE: "stream:media_call_newsletter",
		0x1BF: "stream:media_call_newsletter_subscribe",
		0x1C0: "stream:media_call_newsletter_unsubscribe",
		0x1C1: "stream:media_call_newsletter_message",
		0x1C2: "stream:media_call_newsletter_reaction",
		0x1C3: "stream:media_call_business",
		0x1C4: "stream:media_call_business_catalog",
		0x1C5: "stream:media_call_business_product",
		0x1C6: "stream:media_call_business_order",
		0x1C7: "stream:media_call_business_cart",
		0x1C8: "stream:media_call_business_payment",
		0x1C9: "stream:media_call_business_shipping",
		0x1CA: "stream:media_call_business_address",
		0x1CB: "stream:media_call_business_contact",
		0x1CC: "stream:media_call_business_hours",
		0x1CD: "stream:media_call_business_website",
		0x1CE: "stream:media_call_business_email",
		0x1CF: "stream:media_call_business_phone",
		0x1D0: "stream:media_call_business_category",
		0x1D1: "stream:media_call_business_description",
		0x1D2: "stream:media_call_business_name",
		0x1D3: "stream:media_call_business_verified",
		0x1D4: "stream:media_call_business_identity",
		0x1D5: "stream:media_call_business_certificate",
		0x1D6: "stream:media_call_business_quick_reply",
		0x1D7: "stream:media_call_business_greeting",
		0x1D8: "stream:media_call_business_away",
		0x1D9: "stream:media_call_business_label",
		0x1DA: "stream:media_call_business_automation",
		0x1DB: "stream:media_call_business_flow",
		0x1DC: "stream:media_call_business_template",
		0x1DD: "stream:media_call_business_button",
		0x1DE: "stream:media_call_business_list",
		0x1DF: "stream:media_call_business_carousel",
		0x1E0: "stream:media_call_business_single_product",
		0x1E1: "stream:media_call_business_multi_product",
		0x1E2: "stream:media_call_business_address_message",
		0x1E3: "stream:media_call_business_contact_message",
		0x1E4: "stream:media_call_business_location_message",
		0x1E5: "stream:media_call_business_call_button",
		0x1E6: "stream:media_call_business_quick_reply_button",
		0x1E7: "stream:media_call_business_url_button",
	}

	for k, v := range doubleTokens {
		tm.doubles[k] = v
		tm.attrs[v] = k
	}
}

// GetTagToken returns the token for a tag.
func (tm *TokenMap) GetTagToken(tag string) (uint16, bool) {
	token, ok := tm.tags[tag]
	return token, ok
}

// GetToken returns the token for an attribute.
func (tm *TokenMap) GetToken(attr string) (uint16, bool) {
	token, ok := tm.attrs[attr]
	return token, ok
}

// GetTagString returns the string for a tag token.
func (tm *TokenMap) GetTagString(token uint16) (string, bool) {
	if token <= 0xFF {
		s, ok := tm.singles[token]
		return s, ok
	}
	s, ok := tm.doubles[token]
	return s, ok
}

// GetAttrString returns the string for an attribute token.
func (tm *TokenMap) GetAttrString(token uint16) (string, bool) {
	if token <= 0xFF {
		s, ok := tm.singles[token]
		return s, ok
	}
	s, ok := tm.doubles[token]
	return s, ok
}